name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: 依存関係のインストール
        run: flutter pub get

      - name: 型チェックとlintルール適用
        run: flutter analyze

      - name: KeyStoreファイルを生成
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: key.propertiesを生成
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: |
          printf 'keyAlias=%s\nkeyPassword=%s\nstoreFile=keystore.jks\nstorePassword=%s\n' \
            "$KEY_ALIAS" "$KEY_PASSWORD" "$STORE_PASSWORD" > android/key.properties
          echo "=== key.properties確認 ==="
          cat android/key.properties

      - name: ビルド確認
        run: flutter build apk --flavor=prod --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }} --dart-define=SENTRY_FLUTTER_DSN=${{ secrets.SENTRY_FLUTTER_DSN }} --dart-define=SENTRY_ENVIRONMENT=${{ vars.SENTRY_ENVIRONMENT }}

      - name: テスト実行
        run: flutter test